# Generated by Django 3.0.3 on 2020-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=120)),
                ('todo_name', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
